export const WECHAT_QRCODE_LOGIN_PATH = "/connect/qrconnect"
export const REQUEST_ACCESS_TOKEN_PATH = "/sns/oauth2/access_token"
export const REQUEST_REFRESH_TOKEN_PATH = "/sns/oauth2/refresh_token"
export const CHECK_ACCESS_TOKEN_VALIDITY_PATH = "/sns/auth"
export const REQUEST_USER_INFO_PATH = "/sns/userinfo"